### ISSUE TITLE
Decrypt Yaml List Value

### ISSUE THREAD

**Issue by emoshaya** [carlpett/terraform-provider-sops#103]
I have the following file.yaml

```yaml
sites:
  - url: ENC[AES256_GCM,data:x/wCj4a2uyjKexk5tqXRyFQDir5YS0wgr94mBC7O,iv:GNd28uJ4U9x34kIf92v8au3UZxd57xOASXZW1M4FhBQ=,tag:04DBK6v5IsLPWMlmWG+YxA==,type:str]
    secret: ENC[AES256_GCM,data:e5y1tm95QFuNmBBV7hK2FqhO/6cnYeW02YUcJLr1qiHbofiACcGCMCVY0ZLGaOpeNCy+UJdWuoyHpPI2QglHX+8+sCXikuVS24VLME7GmI8VDZiRTr7XlCWnS5VBo1ZBQbRuEm5+E6bkdaqRSH5vgpOoFqsP5JIPltNsCzePw2w=,iv:Ale015rSC+ekGSynn1eaU7YbVBLm/Ma7Q6F76uh2LkA=,tag:LpLj95062vam4Gi0Sb3RZQ==,type:str]
  - url: ENC[AES256_GCM,data:itTbUvKlQsllvoy2jSySWAd66bhHFQ6hikB/P0Vx,iv:t9VS6fPGA4Yxgcp1XXqzqOZHXd7ID6ioOxnVHkM06Mc=,tag:edOPTAJZ88A+opw7lqUBgw==,type:str]
    secret: ENC[AES256_GCM,data:pxFTGoR3H3Pct/K0X4CqPbSgKyMC2sJ6vgkMQNE/XHXYfm0S2lMkJ9ziJp8XvKLkHXhuKxXbvBM+olBU8D6Z7QVwBw70mq+zySS+D5GgM/HigpU7ZKpjFtvkjQK25zd5rNdh5VKuUJpG33vz0/2DM7W1aGBuGIRGlAARo3zSMEg=,iv:s+YgJTqHCQnq43wc49fcCwp1Mkmy7xL5C3Hqi4SNwcM=,tag:04GpEUXnXBlCMD5rPlzjlg==,type:str]
```

I would like to decrypt the whole list. but when I try `data.sops_file.this.data["sites"]`

I get the following error:

`The given key does not identify an element in this collection value`

How can I decrypt the whole list?
