### ISSUE TITLE
Issue with aws_profile and profiles stored in ~/.aws/config

### ISSUE THREAD

**Issue by mattparkes** [carlpett/terraform-provider-sops#45]
SOPS 3.6 added the ability to use AWS profiles defined in your AWS Config file (not just static credentials defined in `~/.aws/credentials`).

I have upgraded to SOPS 3.6 and have this working in SOPS natively (e.g `aws_profile` in `secrets.yaml` points to a profile defined in `~/.aws/config` and `sops -d secrets.yaml` works):

```
sops -d secrets.yaml
my-password: REDACTED
[...]
my-other-password: REDACTED
```

However it does _not_ work in `terraform-provider-sops`:

```
Error: Error getting data key: 0 successful groups required, got 0
```

**`~/.aws.config`:**
```
[profile my-profile]
region = ap-southeast-2
credential_process = my-helper-script
```

**`secrets.yaml`:**
```
sops:
    kms:
    -   arn: REDACTED
        created_at: '2019-05-13T02:53:09Z'
        enc: REDACTED
        aws_profile: my-profile
```

**`provider.tf`:**
```
provider "sops" {
  version = "0.5.0"
}

data "sops_file" "secrets" {
  source_file = "secrets.yaml"
}
```

I have tried setting the environment variable `AWS_SDK_LOAD_CONFIG=1` but that doesn't help either.
