### ISSUE TITLE
Question: Where does sops_file get credentials for azure_keyvault

### ISSUE THREAD

**Issue by dkirrane** [carlpett/terraform-provider-sops#58]
Where does `sops_file` get Azure credentials when accessing Azure Key Vault?

My files are encruyped using this `.sops.yaml`. Will is use same credentails for all 3 Key Vaults?

```
creation_rules:
  - path_regex: \.(json|yaml)$
    key_groups:
      - azure_keyvault:

          - vaultUrl: 'https://vault-one.vault.azure.net'
            key: 'sops-key'
            version: 'xxxx'

          - vaultUrl: 'https://vault-two.vault.azure.net'
            key: 'sops-key'
            version: 'xxxx'

          - vaultUrl: 'https://vault-three.vault.azure.net'
            key: 'sops-key'
            version: 'xxxx'
```
