### ISSUE TITLE
"Error getting data key: 0 successful groups required, got 0" during Atlantis plan

### ISSUE THREAD

**Issue by byakku** [carlpett/terraform-provider-sops#74]
Hi!

During `terraform plan` I'm getting the following error:

```
Error: Error getting data key: 0 successful groups required, got 0

  on atlantis.tf line 1, in data "sops_file" "secrets":
   1: data "sops_file" "secrets" {
```

I tried different terraform versions, no results. Executing this locally works properly, plan only fails only in the container.

Environment:
-  Provider: GCP
-  Host: GKE
-  Atlantis: `v0.17.0` + Google SDK + Sops installed on container
-  Terraform versions: `0.13.7` and `1.0.5` both tested, same error
-  sops provider: `0.6.3`

atlantis.tf
```tf
data "sops_file" "secrets" {
  source_file = "atlantis_secrets.sops.yaml"
}


resource "helm_release" "atlantis" {
  name             = "atlantis"
  repository       = "https://runatlantis.github.io/helm-charts"
  chart            = "atlantis"
  namespace        = "atlantis"
  create_namespace = true
  version          = "3.14.0"
  wait             = false

  values = [
    file("atlantis_values.yaml")
  ]

[shrinked, github tokens are here]
}
```
sopsed file, data/tokens redacted, in the file I have GH related secrets
```
user: ENC[AES256_GCM,data:...,tag:...,type:str]
token: ENC[AES256_GCM,data:...,iv:...,tag:...,type:str]
secret: ENC[AES256_GCM,data:...,iv:...,tag:...,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/.../locations/global/keyRings/.../cryptoKeys/...-key
          created_at: "2021-08-05T15:18:30Z"
          enc: ...
```

custom values.yaml
```
environmentRaw: 
  - name: GOOGLE_APPLICATION_CREDENTIALS
    value: /var/secrets/atlantis-gcp-secret/credentials.json
  - name: KUBECONFIG
    value: /home/atlantis/.kube/config
  - name: ATLANTIS_REPO_CONFIG_JSON
    value: |
      {"repos":[{"id":"/.*/","pre_workflow_hooks":[{"run":"gcloud auth activate-service-account atlantis@myorg.iam.gserviceaccount.com \\\n  --key-file=/var/secrets/atlantis-gcp-secret/credentials.json"}]}]}
```

SA Activation was needed in order to have working helm provider at GKE. 

Atlantis has `Editor` permissions in GCP, so it has R/W access to all resources. 

Dockerfile:
```
FROM runatlantis/atlantis:v0.17.0 

RUN apk add python3 wget vim 
# Downloading and installing gcloud package
RUN curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz \
  && mkdir -p /usr/local/gcloud \
  && tar -C /usr/local/gcloud -xf /tmp/google-cloud-sdk.tar.gz \
  && /usr/local/gcloud/google-cloud-sdk/install.sh \
  && rm -rf /tmp/google-cloud-sdk.tar.gz \ 
  && curl -L https://github.com/mozilla/sops/releases/download/v3.7.1/sops-v3.7.1.linux > /tmp/sops \
  && mv /tmp/sops /usr/local/bin/sops && chmod +x /usr/local/bin/sops

# Adding the package path to local
ENV PATH $PATH:/usr/local/gcloud/google-cloud-sdk/bin

COPY atlantis/global/kubeconfig /home/atlantis/.kube/config
```
---

Do you have any idea if it's related to sops or the provider itself, or how I can debug this further? 

Logs with DEBUG level didn't show anything really helpful.

Cheers
