### ISSUE TITLE
`null` is converted to `<nil>` string

### ISSUE THREAD

**Issue by chroju** [carlpett/terraform-provider-sops#94]
`null` is converted to `<nil>` string, not `null`.

## Reproduction

`test.yaml` encrypted with sops.

```yaml
password: ENC[AES256_GCM,data:GEa2g3G5,iv:gn0oAKxOx32isGKTnpUMJRnZd6jf7rOcuPBfsSbjFL0=,tag:VsJHLc2BPNF7saoEitccAA==,type:str]
null_value: null
sops:
    kms:
...
```

Terraform config is below.

```hcl
data "sops_file" "test" {
  source_file = "test.yaml"
}

resource "aws_s3_bucket" "foo" {
  bucket = "chroju-20230103"
  policy = data.sops_file.test.data.null_value
}
```

## Expected behavior

`policy` is treated as `null` and `terraform plan` command succeeds.

## Actual behavior

This error message.

```
│ Error: "policy" contains an invalid JSON: invalid character '<' looking for beginning of value
│
│   with aws_s3_bucket.foo,
│   on s3.tf line 7, in resource "aws_s3_bucket" "foo":
│    7:   policy = data.sops_file.test.data.null_value
│
```

If you expand a `null_value` in a string like `bucket = "chroju-20230103-${data.sops_file.test.data.null_value}`, you can see how it is actually treated and see that it is treated as `<nil>` string.

```
│ Error: validating S3 Bucket (chroju-20230103-<nil>) name: only lowercase alphanumeric characters and hyphens allowed in "chroju-20230103-<nil>"
```
